import { SCARCITY_METRIC_BY_ID } from "./methodology";
import type {
  ScarcityDataset,
  ScarcityMetricId,
  ScarcityObservation,
} from "./types";

const values: Record<string, Record<ScarcityMetricId, number>> = {
  gold: {
    "inventory-days": 180,
    "supply-balance-pct": -1,
    "demand-growth-yoy-pct": 2,
    "supply-growth-yoy-pct": 1,
    "regional-premium-pct": 1,
    "reserve-life-years": 55,
    "development-lead-time-years": 12,
    "top-three-supply-share-pct": 33,
    "byproduct-dependency-pct": 12,
    "recycling-share-pct": 28,
    "substitution-ease-score": 40,
  },
  silver: {
    "inventory-days": 70,
    "supply-balance-pct": 7,
    "demand-growth-yoy-pct": 5,
    "supply-growth-yoy-pct": 1,
    "regional-premium-pct": 3,
    "reserve-life-years": 20,
    "development-lead-time-years": 8,
    "top-three-supply-share-pct": 55,
    "byproduct-dependency-pct": 70,
    "recycling-share-pct": 18,
    "substitution-ease-score": 35,
  },
  copper: {
    "inventory-days": 45,
    "supply-balance-pct": 6,
    "demand-growth-yoy-pct": 4,
    "supply-growth-yoy-pct": 1,
    "regional-premium-pct": 7,
    "reserve-life-years": 40,
    "development-lead-time-years": 12,
    "top-three-supply-share-pct": 55,
    "byproduct-dependency-pct": 15,
    "recycling-share-pct": 30,
    "substitution-ease-score": 25,
  },
  uranium: {
    "inventory-days": 24,
    "supply-balance-pct": 9,
    "demand-growth-yoy-pct": 6,
    "supply-growth-yoy-pct": 2,
    "regional-premium-pct": 12,
    "reserve-life-years": 75,
    "development-lead-time-years": 15,
    "top-three-supply-share-pct": 65,
    "byproduct-dependency-pct": 5,
    "recycling-share-pct": 5,
    "substitution-ease-score": 15,
  },
  cobalt: {
    "inventory-days": 35,
    "supply-balance-pct": 2,
    "demand-growth-yoy-pct": 4,
    "supply-growth-yoy-pct": 6,
    "regional-premium-pct": 15,
    "reserve-life-years": 35,
    "development-lead-time-years": 8,
    "top-three-supply-share-pct": 80,
    "byproduct-dependency-pct": 65,
    "recycling-share-pct": 20,
    "substitution-ease-score": 45,
  },
  lithium: {
    "inventory-days": 120,
    "supply-balance-pct": -5,
    "demand-growth-yoy-pct": 12,
    "supply-growth-yoy-pct": 18,
    "regional-premium-pct": -3,
    "reserve-life-years": 90,
    "development-lead-time-years": 6,
    "top-three-supply-share-pct": 70,
    "byproduct-dependency-pct": 10,
    "recycling-share-pct": 5,
    "substitution-ease-score": 50,
  },
  platinum: {
    "inventory-days": 40,
    "supply-balance-pct": 4,
    "demand-growth-yoy-pct": 2,
    "supply-growth-yoy-pct": -1,
    "regional-premium-pct": 5,
    "reserve-life-years": 30,
    "development-lead-time-years": 10,
    "top-three-supply-share-pct": 85,
    "byproduct-dependency-pct": 70,
    "recycling-share-pct": 25,
    "substitution-ease-score": 45,
  },
  palladium: {
    "inventory-days": 150,
    "supply-balance-pct": -8,
    "demand-growth-yoy-pct": -5,
    "supply-growth-yoy-pct": 2,
    "regional-premium-pct": -2,
    "reserve-life-years": 35,
    "development-lead-time-years": 10,
    "top-three-supply-share-pct": 80,
    "byproduct-dependency-pct": 75,
    "recycling-share-pct": 30,
    "substitution-ease-score": 60,
  },
};

const observedAt = "2026-08-01T00:00:00.000Z";
const publishedAt = "2026-08-02T00:00:00.000Z";

const observations: ScarcityObservation[] = Object.entries(values).flatMap(
  ([metalId, metricValues]) => Object.entries(metricValues).map(([metricId, value]) => ({
    id: `sample:${metalId}:${metricId}:2026-08-01`,
    datasetId: "sample-v1",
    metalId,
    metricId: metricId as ScarcityMetricId,
    value,
    unit: SCARCITY_METRIC_BY_ID[metricId as ScarcityMetricId].unit,
    observedAt,
    publishedAt,
    sourceId: "illustrative-fixture",
    status: "estimated" as const,
    coverageRatio: 1,
    independentSourceCount: 1,
    notes: "Illustrative development value. It must not be displayed as real market data.",
  })),
);

export const SAMPLE_SCARCITY_DATASET: ScarcityDataset = Object.freeze({
  id: "sample-v1",
  label: "Illustrative development fixture",
  kind: "sample",
  description: "Synthetic values for local development and tests. Not current or historical market data.",
  sources: [{
    id: "illustrative-fixture",
    name: "Illustrative fixture — not market data",
    kind: "sample" as const,
    notes: "Synthetic values used only to validate calculations and interface contracts.",
  }],
  observations,
});

export const EMPTY_SCARCITY_DATASET: ScarcityDataset = Object.freeze({
  id: "production-empty-v1",
  label: "Production observation store",
  kind: "empty",
  description: "No verified production observations have been ingested yet.",
  sources: [],
  observations: [],
});
